name: Build

on:
  push:
    branches:
    - '**'

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
